### PR TITLE
implement isdefined(Base, :symbol)

### PR DESCRIPTION
**Pull request by KristofferC**
Should be enough to fill in the version ranges for when the symbols are defined now.

Could either:

* Look through all uses of `isdefined(Base, :Symbol)` in registered Julia packages.
* Automatically search through Base for every commit and build up the table. Might be a bit overkill?

### CODE REVIEW

**Comment by KristofferC** [comment]
Probable needs to support `&&` format as well, e.g. `isdefined(Base, :__precompile__) && __precompile__()`

**Comment by KristofferC** [comment]
Should also handle e.g. `Symbol("@__DIR__")`

**Comment by KristofferC** [comment]
This seems to be the usage of `isdefined(Base, :symbol)` in all registered packages:

https://gist.github.com/KristofferC/2340fd23120f5ee5789845769bd0f90e

**Comment by Keno** [comment]
Needs a rebase

**Comment by Keno** [comment]
Good to go?

**Comment by KristofferC** [comment]
Should be. The isdefined database is still rather small but doesn't hurt to try this out with the once that are included.

**Pull request merged**
